### ISSUE TITLE
HUD bug report

### ISSUE THREAD

**Issue by Nevvy** [AsianAntwan/AntsHUD#1]
Hi
Please fix it soldier bar metters (1280x720, 16:9) + taunt menu is glitched. Its invisible
http://images.akamai.steamusercontent.com/ugc/101727053555115303/4598AA2B456703C5AB07601323B053C11B12E19A/

**Comment by Nevvy** [comment]
Btw player avatars on casual are glitched. They are on left side

**Comment by AsianAntwan** [comment]
Welp, let's see if I can fix the overdue bug.
