### ISSUE TITLE
I can't see how much money I have.

### ISSUE THREAD

**Issue by ItsTeraBytes** [AsianAntwan/AntsHUD#7]
I tried reloading TF2 and reinstalling AntHUD twice. My customization are CenteredMetal_BelowCrosshair, 4.3RatioFix_ClassLoadoutPanel, 32Player_ScoreBoard and TransparentViewmodels_hudlayout. If that helps.
![hl2_T0n2BDlMgE](https://user-images.githubusercontent.com/88017555/206855470-91303480-8184-4739-9cb4-5bb0130cd891.png)

**Comment by AsianAntwan** [comment]
Fixed. Apparently the element was moved to hudlayout.res on TF2's default HUD, so I updated it accordingly.
